#!/bin/bash

echo "🐳 Docker Commands for QURSE Project"
echo "====================================="
echo ""
echo "📦 Build the production Docker image:"
echo "   docker build -t qurse-app ."
echo ""
echo "🔧 Build the development Docker image:"
echo "   docker build -f Dockerfile.dev -t qurse-dev ."
echo ""
echo "🚀 Run production container:"
echo "   docker run -p 3000:3000 qurse-app"
echo ""
echo "🚀 Run development container:"
echo "   docker run -p 3001:3000 qurse-dev"
echo ""
echo "🔄 Use Docker Compose - Production:"
echo "   docker-compose up qurse-app --build"
echo ""
echo "🔄 Use Docker Compose - Development:"
echo "   docker-compose up qurse-dev --build"
echo ""
echo "🔄 Use Docker Compose - Both services:"
echo "   docker-compose up --build"
echo ""
echo "⏹️  Stop containers:"
echo "   docker-compose down"
echo ""
echo "📊 View running containers:"
echo "   docker ps"
echo ""
echo "🧹 Clean up unused images:"
echo "   docker system prune -a"
echo ""
echo "📝 View logs:"
echo "   docker-compose logs -f qurse-app"
echo "   docker-compose logs -f qurse-dev"
echo ""
echo "🔍 Debug container:"
echo "   docker exec -it <container_id> /bin/sh"
echo ""
echo "💡 Quick Start (Development):"
echo "   ./docker-commands.sh && docker-compose up qurse-dev --build"
